In [1]:
import numpy as np

In [22]:
my_list1 = [1,2,3,4]

In [23]:
my_array1 = np.array(my_list1)

In [24]:
my_array1

array([1, 2, 3, 4])

In [25]:
my_list2 = [11,22,33,44]

In [26]:
my_lists = [my_list1, my_list2]

In [27]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [28]:
my_array2 = np.array(my_lists)

In [29]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [30]:
my_array2.dtype

dtype('int64')

In [31]:
my_array2.shape

(2, 4)

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
my_zeros = np.zeros(5)

In [34]:
my_zeros.dtype

dtype('float64')

In [40]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [47]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [48]:
np.arange(3,43,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [49]:
5/2

2.5

In [50]:
5+2

7

In [51]:
5-2

3

In [52]:
5*2

10

In [53]:
5%2

1

In [54]:
5%%2

SyntaxError: invalid syntax (<ipython-input-54-669c245ac925>, line 1)

In [55]:
5//2

2

In [56]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [58]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [59]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [60]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [61]:
arr1 + arr1

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [62]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
arr1/arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [66]:
8/arr1*arr1

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [67]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [68]:
arr1**2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [69]:
arr=np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr[8]

8

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[1:5]

array([1, 2, 3, 4])

In [74]:
arr[3:6]

array([3, 4, 5])

In [75]:
arr[0:5]=100

In [76]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [92]:
arr[0:6]=[0,1,2,3,4,5]

In [78]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
slice_arr=arr[0:6]

In [81]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [89]:
slice_arr[:]=99

In [83]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [84]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr_copy=arr.copy()

In [88]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [91]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [95]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [97]:
arr_2d[1]

array([20, 25, 30])

In [98]:
arr_2d[1][0]

20

In [99]:
arr_2d[1,0]

20

In [100]:
arr_2d


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [101]:
arr_2d[0,1]

10

In [103]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [104]:
arr_2d[2,1]

40

In [105]:
arr_2d[2]

array([35, 40, 45])

In [107]:
arr_2d[1,:]

array([20, 25, 30])

In [108]:
arr_2d=np.zeros((10,10))

In [109]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [112]:
arr_length=arr_2d.shape[1]

In [113]:
arr_length

10

In [114]:
for i in range(arr_length):
        arr_2d[i]=i

In [115]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [116]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [117]:
arr_2d[[6,4,1,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])